### ISSUE TITLE
Create polymorphic (generic) action creator

### ISSUE THREAD

**Issue by anilanar** [the-dr-lazy/deox#149]
I have created an action such as:

```ts
export const foo = createAction(
  'FOO',
  resolve => <S extends string>(s: S) => resolve(s),
);
```

The action type is correct, the output function has the correct generic constraints and types.

However, using such an action creator with `createReducer` causes type of action to be `never` in the handler function.

**This is a simplified version of the actual use case.** We really do use polymorphic actions in a useful way.

**Comment by thebrodmann** [comment]
This looks like as a design limitation in TypeScript.

I don't see anyway to infer polymorphic action type.

```ts
declare const foo: <S extends string>(s: S) => { type: 'FOO', payload: S }

type Action = ReturnType<typeof foo> //=> any
```

@anilanar do you have any idea?

**Comment by anilanar** [comment]
You are right @the-dr-lazy, it's currently not possible.
