### ISSUE TITLE
Bundle size notes

### ISSUE THREAD

**Issue by TNikolai** [the-dr-lazy/deox#151]
@the-dr-lazy  First of all, thank you for this project, this is what I searched, but every time when I would install any dependency in the project I measure its size in [bundlephobia](https://bundlephobia.com).

[redux-actions](https://bundlephobia.com/result?p=redux-actions@2.6.5)  - **7kB** 
[deox](https://bundlephobia.com/result?p=deox@3.2.1) - **23kB**

Is it expected to have bundle size X3 than the initial redux-actions library, or maybe some build steps and dependencies can be optimized?

**Comment by the-dr-lazy** [comment]
Thank you for reaching.
If I be right, that huge size is due to dependency of `configureStore` to the `redux-starter-kit library`. If you don't use it, it will tree shake and you will not gain any size from that.

As you can see in the screenshot, the actual functionality of the library is not that huge.

![Screen Shot 2020-09-04 at 11 11 29 PM](https://user-images.githubusercontent.com/20781126/92275216-f904c080-ef03-11ea-9018-316beeab77c7.png)

**Comment by TNikolai** [comment]
Yes, as I can see it is used in [examples](https://github.com/the-dr-lazy/deox/blob/master/examples/tasks/src/index.tsx#L6).
If it is only the place where configure store is needed, maybe it is an option to have 2 separate build steps one for examples with connfigureStore and another just for the deox lib without additional libs. Probably [tsconfig includes line should be updated](https://github.com/the-dr-lazy/deox/blob/master/tsconfig.json#L2) and one more build step added for package.json scripts.

**Comment by the-dr-lazy** [comment]
Why we should care about usage of `configureStore`? If any user of package doesn't use it, it should tree shake.
I didn't decided yet but maybe I'll go for a breaking change to remove `configureStore`. Anyone wants to use it then can simply install `redux-starter-kit` and go on.

**Comment by TNikolai** [comment]
--How does includes TSC option affect bundle size? It's strange, did you tested it?
 No, I didn't test it, I thought TSC.includes an option used for the build but that is wrong it is used only TS compilation.

**Comment by DCzajkowski** [comment]
The problem we are having at this point, is that we don't have tree-shaking implemented and it seems like deox is pulling in rxjs and redux-starter-kit. So from my perspective, removing it from the core would be a good choice 😅
