### ISSUE TITLE
Why was Deox deprecated?

### ISSUE THREAD

**Issue by dannypule** [the-dr-lazy/deox#160]
Is this message somehow an error? 

https://www.npmjs.com/package/deox

![image](https://user-images.githubusercontent.com/8937911/96309589-85bf9580-0ffd-11eb-826a-306cee597a8f.png)

**Comment by the-dr-lazy** [comment]
Version 3.3.0 has been deprecated due to a bug introduced in #153. It's gonna be fixed in #159.
