### ISSUE TITLE
Prototype pollution in immer dependency

### ISSUE THREAD

**Issue by Michael-1** [the-dr-lazy/deox#164]
Deox currently depends on _redux-starter-kit_, which depends on a version of _immer_ for which a high-severity security issue was reported (see [Github advisory](https://github.com/advisories/GHSA-9qmh-276g-x5pj)).

The solution is to switch to the latest version of _@reduxjs/toolkit_ (the successor of _redux-starter-kit)._

**Comment by the-dr-lazy** [comment]
As noted in https://github.com/the-dr-lazy/deox/issues/151#issuecomment-687367481 I decided to drop the dependency on _redux-starter-kit_. PRs welcome.
